import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased custom-bg`}
      >
         {/* Vídeo de fundo */}
         <div className="fixed inset-0 -z-10 overflow-hidden">
          <video
            autoPlay
            loop
            muted
            playsInline
            className="absolute inset-0 w-full h-full object-cover"
          >
            <source
              src="https://cdn.coverr.co/videos/coverr-bulldozer-on-construction-site-3202/1080p.mp4"
              type="video/mp4"
            />
            Seu navegador não suporta vídeos HTML5.
          </video>
          
          {/* Overlay para escurecer o vídeo */}
          <div className="absolute inset-0 bg-black/60"></div>
        </div>

        {/* Conteúdo principal */}
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
